#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: nordible blog

# Short bio or description (displayed in the header)
description: direction obsessed

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.gravatar.com/avatar/9f0e86127334688292f2c7928b0750e7

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  # dribbble:
  email: info@nordible.com
  facebook: https://facebook.com/nordible
  # flickr:
  github: nordible
  #instagram:
  #linkedin: # xameeramir
  #pinterest:
  rss: http://xameeramir.github.io # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: nordiblehq
  # stackoverflow: # your stackoverflow profile, e.g. "users/2404470/xameeramir"
  # youtube: # channel/<your_long_string> or user/<user-name>
  # googleplus:  anything in your profile username that comes after plus.google.com/
  # google: nordible

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: xameeramir

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-109226104-1


# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://xameeramir.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

#Show 5 posts each page 
paginate: 5
paginate_path: "/index/page:num/"

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
